// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  require.config({
    paths: {
      'jquery': 'lib/jquery',
      'easel': 'lib/easel',
      'underscore': 'lib/underscore',
      'backbone': 'lib/backbone',
      'globals': 'lib/modules/js/globals',
      'utilities': 'lib/modules/js/utilities',
      'board': 'lib/modules/js/board',
      'controls': 'lib/modules/js/controls',
      'player': 'lib/modules/js/player',
      'npc': 'lib/modules/js/npc'
    }
  });

  define(['utilities', 'board', 'player', 'npc', 'globals'], function(ut, board, PC, NPC, globals) {
    return createjs.Ticker.addEventListener("tick", board.stage);
  });

}).call(this);
