// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    urlArgs: "bust=" + (new Date()).getTime(),
    paths: {
      'jquery': 'lib/jquery',
      'easel': 'lib/easel',
      'underscore': 'lib/underscore',
      'backbone': 'lib/backbone',
      'globals': 'lib/modules/js/globals',
      'utilities': 'lib/modules/js/utilities',
      'dialog': 'lib/modules/js/dialog',
      'board': 'lib/modules/js/board',
      'controls': 'lib/modules/js/controls',
      'player': 'lib/modules/js/player',
      'npc': 'lib/modules/js/npc',
      'taskrunner': 'lib/modules/js/taskrunner'
    }
  });

  define(['utilities', 'board', 'player', 'npc', 'taskrunner'], function(ut, board, PC, NPC, taskrunner) {
    taskrunner.initialize(board);
    return board.initialize(taskrunner);
  });

}).call(this);
