// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  require.config({
    paths: {
      'jquery': 'lib/jquery',
      'easel': 'lib/easel',
      'underscore': 'lib/underscore',
      'backbone': 'lib/backbone',
      'utilities': 'lib/modules/js/utilities',
      'board': 'lib/modules/js/board',
      'controls': 'lib/modules/js/controls',
      'player': 'lib/modules/js/player',
      'npc': 'lib/modules/js/npc'
    }
  });

  define(['utilities', 'controls', 'board', 'player', 'npc'], function(ut, board, PC, NPC) {});

}).call(this);
