// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("listening on " + port);
  });

  app.configure(function() {
    app.use(express.logger("dev"));
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](__dirname + "/public"));
  });

  app.get("/", function(req, res) {
    return res.render("index");
  });

}).call(this);
