// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "underscore"], function() {
    var destroyModal, launchModal;
    if (typeof Object.create !== "function") {
      Object.create = function(o) {
        var F;
        F = function() {};
        F.prototype = o;
        return new F();
      };
    }
    launchModal = function(content, options) {
      var defaults, modal;
      destroyModal(true);
      defaults = {
        close: true,
        destroyHash: false
      };
      options = $.extend(defaults, options);
      modal = $("<div />").addClass("modal");
      try {
        if ($.isArray(content)) {
          $.each(content, function(index, item) {
            return modal.append(item);
          });
        } else {
          modal.html(content);
        }
      } catch (_error) {}
      if (options.close !== false) {
        modal.prepend("<i class='close-modal'>X</i>");
        modal.find(".close-modal").on("click", function() {
          return destroyModal(null, options);
        });
      }
      $(document.body).addClass("active-modal").append(modal);
      return modal;
    };
    destroyModal = function(existing, options) {
      options = $.extend({
        destroyHash: false
      }, options);
      return $(".modal").fadeOut("fast", function() {
        if (existing !== true) {
          $(document.body).removeClass("active-modal");
          if (options.destroyHash === true) {
            return window.location.hash = "";
          }
        }
      });
    };
    ({
      l: function(x, y) {
        return x > 0;
      },
      r: function(x, y) {
        return x < 0;
      },
      t: function(x, y) {
        return y > 0;
      },
      b: function(x, y) {
        return y < 0;
      },
      rl: function(x, y) {
        return l(x, y) || r(x, y);
      },
      tl: function(x, y) {
        return l(x, y) || t(x, y);
      },
      bl: function(x, y) {
        return l(x, y) || b(x, y);
      },
      trl: function(x, y) {
        return l(x, y) || r(x, y) || t(x, y);
      },
      rbl: function(x, y) {
        return l(x, y) || r(x, y) || b(x, y);
      },
      rbl: function(x, y) {
        return l(x, y) || b(x, y) || t(x, y);
      },
      tr: function(x, y) {
        return r(x, y) || t(x, y);
      },
      rb: function(x, y) {
        return r(x, y) || b(x, y);
      },
      trb: function(x, y) {
        return b(x, y) || r(x, y) || t(x, y);
      },
      tb: function(x, y) {
        return b(x, y) || t(x, y);
      }
    });
    return {
      c: function() {
        var arg, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          _results.push(console.log(arg));
        }
        return _results;
      },
      create: Object.create,
      addEventListeners: function(obj, events) {
        return _.each(events, function(fn, name) {
          return obj.addEventListener(name, fn);
        });
      },
      underline: function(ctx, text, x, y, size, color, thickness, offset) {
        var width;
        width = ctx.measureText(text).width;
        switch (ctx.textAlign) {
          case "center":
            x -= width / 2;
            break;
          case "right":
            x -= width;
        }
        y += size + (offset || 1);
        ctx.beginPath();
        ctx.strokeStyle = color || "#fff";
        ctx.lineWidth = thickness || 2;
        ctx.moveTo(x, y);
        ctx.lineTo(x + width, y);
        return ctx.stroke();
      },
      launchModal: function(content, options) {
        return launchModal(content, options);
      },
      destroyModal: function(existing, options) {
        return destroyModal(existing, options);
      },
      tileEntryCheckers: {
        l: function(x, y) {
          return x > 0;
        },
        r: function(x, y) {
          return x < 0;
        },
        t: function(x, y) {
          return y > 0;
        },
        b: function(x, y) {
          return y < 0;
        },
        rl: function(x, y) {
          return l(x, y) || r(x, y);
        },
        tl: function(x, y) {
          return l(x, y) || t(x, y);
        },
        bl: function(x, y) {
          return l(x, y) || b(x, y);
        },
        trl: function(x, y) {
          return tr(x, y) || l(x, y);
        },
        rbl: function(x, y) {
          return l(x, y) || rb(x, y);
        },
        tr: function(x, y) {
          return r(x, y) || t(x, y);
        },
        rb: function(x, y) {
          return r(x, y) || b(x, y);
        },
        trb: function(x, y) {
          return tr(x, y) || b(x, y);
        },
        tb: function(x, y) {
          return b(x, y) || t(x, y);
        }
      }
    };
  });

}).call(this);
